// <auto-generated />
using System;
using DailyQuotes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DailyQuotes.Migrations
{
    [DbContext(typeof(QuoteContext))]
    [Migration("20200705085425_quote_positions_added")]
    partial class quote_positions_added
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("DailyQuotes.Data.Model.Setting", b =>
                {
                    b.Property<int>("SettingKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastPositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastPositionY")
                        .HasColumnType("INTEGER");

                    b.HasKey("SettingKey");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("DailyQuotes.Data.Models.Quote", b =>
                {
                    b.Property<int>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("lastItemIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("totalCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuoteId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("DailyQuotes.Data.Models.Result", b =>
                {
                    b.Property<string>("_id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QuoteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("author")
                        .HasColumnType("TEXT");

                    b.Property<string>("content")
                        .HasColumnType("TEXT");

                    b.Property<int>("length")
                        .HasColumnType("INTEGER");

                    b.HasKey("_id");

                    b.HasIndex("QuoteId");

                    b.ToTable("Result");
                });

            modelBuilder.Entity("DailyQuotes.Data.Models.Result", b =>
                {
                    b.HasOne("DailyQuotes.Data.Models.Quote", null)
                        .WithMany("results")
                        .HasForeignKey("QuoteId");
                });
#pragma warning restore 612, 618
        }
    }
}
